export const DOCUMENTS = ['Election of Benefit', 
    'Initial Certification', 
    'Recertification',
    'F2F Encounter', 
    'F2F Addendum',
    'RN Initial Assessment', 
    'Social Worker Initial Assessment', 
    'Chaplain Initial Assessment',
    'Physician / Referring Notes',
    'Plan of Care', 
    'IDG Notes', 
    'Visit Notes', 
    'Phone Notes',
    'Medication List / MAR', 
    'Labs / Imaging', 
    'Other Supporting Documents'];

